Repository RTByte/rtbyte, pull requests merged in 2020-08, with the labels that each got.

#144 Sentry patches 2020-08-24
  src/commands/Management/logs.js
  src/events/rtbyteMessageUpdate.js
  src/lib/structures/ModEmbed.js
Labels: Meta: Bugfix, Priority: Medium, Status: Ready for review

#151 Autoresponder feature
  src/commands/Management/autoresponder.js
  src/commands/Management/logs.js
  src/events/autoResponseCreate.js
  src/events/autoResponseDelete.js
  src/events/autoResponseUpdate.js
  src/languages/en-US.js
  src/lib/structures/schemas/defaultGuildSchema.js
  src/monitors/autoResponder.js
Labels: Meta: Feature, Priority: Medium, Status: Ready for review

#152 fix to log entry being undefined on guild member updated
  src/events/rtbyteGuildMemberUpdate.js
Labels: Bug: Fixed, Meta: Bugfix, Priority: Low, Status: Ready to merge

#156 Patches 2020-08-28
  src/commands/Management/autoresponder.js
  src/commands/Management/customcmds.js
  src/monitors/autoResponder.js
Labels: Meta: Bugfix, Priority: Medium, Status: Ready for review

#158 switched to users.fetch for #157
  src/extendables/KlasaGuild/fn_KlasaGuild#rtbyteInit.js
Labels: Meta: Bugfix, Status: Ready to merge
